const access_token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhZ3VzQGJjci5pbyIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY2NTcxMjYxMH0.DH-bbvCiNivlnMi-a2HIUCchUJJNGPeRK55U4mJcgdI"

export default access_token
