const access_token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhZ3VzQGJjci5pbyIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY2NTY3MTk5OX0.MRsEcVjPOnXscQk65FbsoTNQcQLrL_1-UWrZFUhfQ7Y"

export default access_token
