const TYPES = {
  POST_LOGIN: "POST_LOGIN",
  GET_CARS: "GET_CARS",
  GET_CAR: "GET_CAR",
  GET_ORDERS: "GET_ORDERS",
  GET_DATA_ORDER: "GET_DATA_ORDER",
  SHOW: "SHOW",
  SEARCH_TERM: "SEARCH_TERM",
}

export default TYPES
