const TYPES = {
  POST_LOGIN: "POST_LOGIN",
  GET_CARS: "GET_CARS",
  GET_CAR: "GET_CAR",
  GET_ORDERS: "GET_ORDERS",
  // monthly order
  GET_SEP_ORDER: "GET_SEP_ORDER",
  GET_OCT_ORDER: "GET_OCT_ORDER",
  GET_NOV_ORDER: "GET_NOV_ORDER",
  GET_DEC_ORDER: "GET_DEC_ORDER",
  // daily order
  GET_SEP_DAILY_ORDER: "GET_SEP_DAILY_ORDER",
  GET_OCT_DAILY_ORDER: "GET_OCT_DAILY_ORDER",
  GET_NOV_DAILY_ORDER: "GET_NOV_DAILY_ORDER",
  GET_DEC_DAILY_ORDER: "GET_DEC_DAILY_ORDER",

  //
  SHOW: "SHOW",
  SEARCH_TERM: "SEARCH_TERM",
}

export default TYPES
