const TYPES = {
  POST_LOGIN: "POST_LOGIN",
  GET_RENTED_CAR_MONTH: "GET_RENTED_CAR_MONTH",
  GET_RENTED_CAR_DAY: "GET_RENTED_CAR_DAY",
  THE_MONTH: "THE_MONTH",
  SHOW: "SHOW",
}

export default TYPES
